CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    firstname VARCHAR(255),
    lastname VARCHAR(255),
    username VARCHAR(255),
    email VARCHAR(255) UNIQUE NOT NULL,
    email_verified TINYINT(1) DEFAULT 0,
    password VARCHAR(255),
    password_confirm VARCHAR(255),
    phonenumber VARCHAR(20),
    role VARCHAR(20),
    last_active TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    languages_spoken JSON,
    languages_learning JSON,
    bio TEXT,
    profile_picture VARCHAR(255),
    location VARCHAR(255),
    learning_goals JSON,
    preferred_language VARCHAR(20),
    time_zone VARCHAR(50),
    account_type VARCHAR(20),
    social_links JSON,
    connections JSON,
    preferred_learning_style VARCHAR(50),
    availability VARCHAR(50),
    achievements JSON,
    progress JSON,
    ratings JSON,
    feedback JSON,
    subscription_status VARCHAR(20),
    payment_method VARCHAR(50),
    notification_preferences JSON,
    two_factor_enabled TINYINT(1) DEFAULT 0,
    privacy_settings JSON

);
